# Generated by Django 3.1.7 on 2021-03-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_auto_20210322_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detector',
            name='file_name',
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos/%Y/%m/%d'),
        ),
    ]
